pipeline:
  name: allow-failure-critical-fails

stages:
  - build

lint:
  stage: build
  image: alpine:3.19
  failures: true
  script:
    - echo "lint passing"

compile:
  stage: build
  image: alpine:3.19
  failures: false
  script:
    - echo "compile running"
    - exit 1
