pipeline:
  name: JAVA-DEBUG
  description: debug java compile

stages:
  - build

compile:
  stage: build
  image: eclipse-temurin:17
  script:
    - mkdir -p out/main
    - javac -d out/main $(find src/main/java -name '*.java')