pipeline:
  name: JAVA-TEST
  description: compile demo

stages:
  - build

compile:
  stage: build
  image: eclipse-temurin:17
  script:
    - ls -R
    - javac src/main/java/com/example/Calculator.java