pipeline:
  name: java-success
  description: A successful Java pipeline

stages:
  - build
  - test

compile:
  stage: build
  script: scripts/compile.sh

run-tests:
  stage: test
  needs: [compile]
  script: scripts/test.sh